### ISSUE TITLE
[ContentUpdates] Data Access Agreement

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#218]
Kim emailed Ann the agreement.

## Introduction
- [x] As confirmed on Feb 28 meeting, the first intro section goes above the agreement.
**TODO - ask Amber to review this again because we did put a lot of that copy within the first Application Terms section. and some of it is written like agreement checkboxes**

![image](https://user-images.githubusercontent.com/18424138/156448556-3a34ba58-093b-4d85-8c1c-14b7a58dc53f.png)
![image](https://user-images.githubusercontent.com/18424138/156448393-6f4db8cb-29b1-498f-b62d-892290bea333.png)

- [x] the second link in this copy is broken in the word doc and should open this in a new tab: https://www.icgc-argo.org/page/136/e83-data-access-compliance-office-policies-and-procedures
![image](https://user-images.githubusercontent.com/18424138/156451333-40678fa0-9e25-435c-a02b-c67a9f297387.png)

## Definition and Agreements
- [x] The rest of the definitions and agreements can be updated using the word doc
![image](https://user-images.githubusercontent.com/18424138/156449854-2c849d93-fc0e-43b5-a248-76581766a78a.png)

- [x] Use the links in the word doc if they work. I confirmed these ones with Amber:
- [x] The definition references this link under ICGC Controlled Data item: **E8.1 Data Access Framework of the Consortium’s Policies and Guidelines**  should open in a new tab: https://www.icgc-argo.org/page/134/e81-data-access-framework 
- [x] In section 21 of the agreement there’s a link to the **Data Breach Policy** should open this in a new tab: https://www.icgc-argo.org/page/137/e84-data-breach-policy 
- [x] At the end of the terms, change Data Access Agreement last updated on: June 12, 2021
to `Data Access Agreement Version 2.0 Published: February 2022`

## Agreeements
As confirmed on Feb 28 meeting, nothing needs to change here. Keep all of the IT agreements for Amber and Judith to review. 
![image](https://user-images.githubusercontent.com/18424138/156453504-202bbe0b-0f0e-4407-9689-483db627fa8c.png)

**Comment by kcullion** [comment]
This looks good for DACO team's review...just waiting on an answer about the weird hyphenation, so I'll leave this here

**Comment by kcullion** [comment]
@anncatton you just missed one of the weird hypenations: 
![image](https://user-images.githubusercontent.com/18424138/158239872-876a9152-f4e8-434c-a452-5666e3ee67d3.png)

**Comment by kcullion** [comment]
I see the correction on QA. Thanks @anncatton 
I think this is ready for review and will open new tickets with their feedback.

**Comment by kcullion** [comment]
I see this update on staging
