### ISSUE TITLE
DACO: Rejecting or Closing an Application

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#393]
- [x] Complete the Rejection flow from DACO Admin action to email to Applicant dashboard card + application state
- [x] Complete the close application flow for pre-approved application
- [x] Complete the close application flow for approved applications
