### ISSUE TITLE
DACO: Annual Attestation 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#394]
- [x] Add attestation flag 
- [x] Add attestation UI
- [x] Add Batch Email infrastructure 
- [x] Build Attestation emails

## Annual attestation notes:
**DACO access is approved for 2 years, but they want applicants to attest after the first year of access - to confirm they agree to the terms**
- [x] 45 days prior to the 1 year mark, an applicant will get an email notifying them they have 45 days to attest or their access is paused
- [x] when the applicant log in they see a message on their dashboard card alerting them to attest  
- [x] the application is in the state it was in before, but there’s an additional yellow banner above it with the agreement test and a button they have to click for attestation
- [x] if the applicant doesn't click the button by the 1 year mark, their access is “paused”. I.e. all people on the application lose access **and the application is locked**.  They receive a message that their access has been paused.
- [x] When they attest, by clicking the button, they see a success message and the application goes back to the “Approved” state. Their access begins again (but expiry date doesn't change from the original expiry date)
- [x] If they do click the button before the 1 year mark, nothing happens to their access, an email is sent, and the application returns to the approved state

**Comment by b-f-chan** [comment]
Successfully deployed all tickets in epic to production!  Closing!
