### ISSUE TITLE
[Data Hookup] Application History Modal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#471]
## Goal
For transparency, DACO wants to have a log of the application history available to the applicant. Each application will have a button that provides all of the state changes of that application, **for the applicant and DACO admin to access**.

Related UI ticket: https://github.com/icgc-argo/dac-ui/issues/470
API tickets: https://github.com/icgc-argo/dac-api/issues/226

## Tasks

- [ ] Make the application number dynamic 
![image](https://user-images.githubusercontent.com/18424138/135471563-801b1faf-966e-469c-9f24-9bbda0ae5710.png)

- [x] Using the API updates (https://github.com/icgc-argo/dac-api/issues/226), hook up the table so that all of the correct data comes through for an application, listing all the states it goes through, starting with creation.
![image](https://user-images.githubusercontent.com/18424138/135471890-0d4da655-cbbc-450d-889d-610c51f09811.png)

- [x] One label change. For the state `REVIEW`, change this in the front end to "Submitted for Review" as it makes more sense in this context
![image](https://user-images.githubusercontent.com/18424138/135472020-2237a3ba-9326-4bcd-9918-ab48374824b7.png)

**Comment by kcullion** [comment]
Tested this in QA, detailed test use cases are on this ticket: https://github.com/icgc-argo/dac-api/issues/226
Works great!

**Comment by kcullion** [comment]
this is working in staging
