### ISSUE TITLE
EPIC: Outstanding Updates for Release

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-ui#537]
# Daco Release Plan 

# Plan
# Pre launch - By 26th April

#### feedback tickets
- [x] min words validation
  - [x] FE [Ciaran] https://github.com/icgc-argo/dac-ui/issues/570 
  - [x] BE [ bashar ] https://github.com/icgc-argo/dac-api/issues/303 
- [x] application terms incomplete UX - Bashar & Ann
  - [x] FE changes - Ann  https://github.com/icgc-argo/dac-ui/issues/571
  - [x] BE changes - Bashar https://github.com/icgc-argo/dac-api/issues/305
- [x] content changes in FE ( Ciaran ) 
  - [x] https://github.com/icgc-argo/dac-ui/issues/569 
  - [x] https://github.com/icgc-argo/dac-ui/issues/568
- [x] Update Section F: Data Access Agreement with the new agreement
- [x] Lay Summary updates - instruction change, max word count, add button for guide link 

### QA Testing starts on 19th end By 22nd April
- [x] cut and deploy master from develop branches
  - [x] BE https://github.com/icgc-argo/dac-api/pull/308
  - [x] FE https://github.com/icgc-argo/dac-ui/pull/584
- [x] increase JWT time in QA to 3 hrs 
- [x] QA testing for everything  
- [x] Deploy to Staging ( tentative )
- [x] Get Judith & Amber's IP address 
- [x] words count BE/FE mismatch issue: icgc-argo/dac-api#312
---
### Deployments - after QA testing, on 25th 
- [x] deploy all daco changes to staging env 
- [x] sign off staging (API, UI)
- [x] deploy all daco changes to prod (API, UI)
- [x] deploy daco2ego for icgc 25k  (Ann)

---
### Final e2e Testing - By 26th eod
- [x] Smoke test & application submission
- [x]  emails
- [x]  content 
- [x] approval 
- [x] rejection
- [x] editing
#### daco2ego testing
- [x] test export
- [x] test users created in ego correctly
  - [x] icgc ego
  - [x] argo ego
#### EGA Testing
- [x] confirm EGA ready with new email format - Email sent again by Ann
- [x] deploy ega cron job in prod
- [x] Test EGA email job (don't send to EGA yet, send to oicr email to confirm contents)
---
### Prod db reset By 28th
- [x] drop collections in mongo
- [x] redeploy the app to reset counters 
- [x] confirm db backup process is in place (devops) 
### IT Items
- [x] Maintenance Page - IT to implement the rules in F5 - help desk ticket [IT-41475](https://servicedesk.oicr.on.ca/servicedesk/customer/portal/2/IT-41475) opened  
  - [x]  we will try to trigger this by taking down ego in prod after hours for brief time
  - the way it works, when ego (i.e. argo is not available) daco won't be available too.
- [x] finish redirect with IT  https://servicedesk.oicr.on.ca/servicedesk/customer/portal/2/IT-41620
  - [x] Test and setup ssh tunnel approach with Henro
  - [x] Setup for Judith
  - [x] Test with IT while redirection is activated
- [x] WONT DO - new coming soon page deployed to netlify https://github.com/icgc-argo/dac-ui/issues/591
    - Kim emailed Amber about this. 
    - Setup for Amber

### More dev fixes by April 29 - May 3rd
- [x] Email changes to approvals based on new instructions: https://github.com/icgc-argo/dac-api/issues/307
    - [x] dac-api v1.3.0 in prod
- [x] won't do - coming soon page tagged
- [x] maintenance mode for dac only
    - [x] dac-ui v1.1.0 in prod

### Pre launch Communication
- [x] WONT DO - schedule with IT the coming soon page to be activated May 9th 
- [x] schedule the redirection landing page with IT to be activated May 16th 
- [x] add Judith to Daco's Help desk Jira - ticket open by Kim [IT-41606]
- [x] Decide on the launch date (Amber wants to send the email 2 weeks prior, using list in the next point)
  - launch date set to May 16th 
- [x] export daco users file to amber to notify them - uploaded by bashar as per Amber's instructions

#### Documentation & Content Work
- [x] Update documentation website - add lay summary guide - Kim - Pending Amber's changes
- [x] Update links on Platform: https://github.com/icgc-argo/platform-ui/issues/2002 
- [x] Make sure ICGC docs content applicable to new website process - links should redirect, so hopefully it should be okay https://github.com/icgc-argo/roadmap/issues/834
----------------------
# May 9th
- [x] Email EGA help desk to update their links to DACO (Kim/Brandon)
- [x] Email Aina from EGA to remind her that we will start sending emails from v2 on launch date (Ann/Bashar)
- [x] check up on Daco2ego - Ann 

# On Launch - 16th May
- [x] open daco v2 to public (devops) 
  - [x] IT to add daco.icgc-argo.org to the public vip & cert  - Ryan
  - [x] Henric will switch ingress class to public and DNS route 53
- [x] block old system
  - [x] activate redirection rule to use the dac ui new website notice [Ryan from IT]
  - [x] make sure redirect page is working (https://daco.icgc-argo.org/new-website-notice) [ Kim/Brandon ]
  - [x] confirm Judith can access the old system with ssh - Email/Call
- [x] publish docs 
  - Docs PRs: https://github.com/icgc-argo/argo-docs/pull/491 and https://github.com/icgc-argo/argo-docs/pull/498
    - [x] merge https://github.com/icgc-argo/argo-docs/pull/504/files
  - [x] ICGC 25K Docs - push these changes live, PR https://github.com/icgc-dcc/dcc-docs/pull/77 
- [x] Switch platform links feature flag to use new daco urls - Ann/Jon https://github.com/OICR/argo-infra/pull/760/files
- [x] switch nightly email configs to EGA email dcc  `dcc_ega@lists.icgc.org` - Ann - redeploy needed
- [x] Update v2 daco report to be at 2:30 am UTC  - cron redeploy needed
----------
# After Launch
- [x] Remove link in argo docs pointing to old system
- [x] Fix apply for daco link in platform 
# None blocking items
- [x] Amber wants us to see if OICR needs to archive anything from the v1 website (legal meeting for discussion on Monday May 16) --> Confirm with @mcourtot 
### Dev items 
- [x] Validation https://github.com/icgc-argo/dac-ui/issues/583  (ready to test in QA)
#### accounts management
- [x] confirm daco email accounts ownership 
### IT Security Audit 
- [x] Daco system brief document (bashar) - sent to IT
- [x] Daco system internal pen test - bashar - https://servicedesk.oicr.on.ca/servicedesk/customer/portal/2/IT-41641
  - started by IT

**Comment by blabadi** [comment]
# Daco Release Plan 
- [ ] add dead lines 
- [ ] add in tickets links where needed

# Plan
# Pre launch
- [ ] export daco users file to amber to notify them 
 - sent IT ticket to confirm file transfer privacy 
 
### Documentation & Content Work
- [ ] Update documentation website - add lay summary guide
- [ ] Update links on Platform: https://github.com/icgc-argo/platform-ui/issues/2002
- [ ] Make sure ICGC docs content applicable to new website process - links should redirect, so hopefully it should be okay https://github.com/icgc-argo/roadmap/issues/834
---
### Dev work
#### feedback tickets
- [ ] min words validation (Ann)
- [ ] application terms incomplete UX - pending Kim's decision
- [ ] content changes in FE ( tbd )
- [x] Update Section F: Data Access Agreement with the new agreement
- [x] Lay Summary updates - instruction change, max word count, add button for guide link 
- [ ] 
#### Refresh token
- [ ] deploy front end & test refresh in dev with lowered expiry for JWTs & Refresh tokens  (Sam)
- [ ] test and sign off refersh token behaviour (Kim)
- [ ] tag FE and do final QA test  
- [ ] evaluate modal approach
#### EGA
- [ ] confirm EGA ready with new email format - pending response from them

---
### Deployments
- [ ] deploy all daco changes to staging env & sign off (API, UI)
- [ ] deploy all daco changes to prod (API, UI)
- [ ] deploy ega cron job in prod
- [ ] deploy daco2ego for icgc 25k  (Ann)
---
### Final e2e Testing:
- [ ] Smoke test & application submission
- [ ]  emails
- [ ]  content 
- [ ] approval 
- [ ] rejection
- [ ] editing
#### daco2ego testing
- [ ] test export
- [ ] test users created in ego correctly
  - [ ] icgc ego
  - [ ] argo ego
#### EGA Testing
- [ ] Test EGA email job (don't send to EGA yet, send to oicr email to confirm contents)
- [ ] switch configs back to EGA email 
---
### Prod db reset 
- [ ] drop collections in mongo
- [ ] redeploy the app to reset counters
----------------------
# On Launch
- [ ] publish docs 
  - Docs PRs: https://github.com/icgc-argo/argo-docs/pull/491 and https://github.com/icgc-argo/argo-docs/pull/498
- [ ] open daco v2 publically (devops) 
- [ ] block old system
  - [ ] activate redirection rule
  - [ ] add IPs for allowed list
- [ ] place holder

**Comment by b-f-chan** [comment]
Just one point to confirm before this Release Ticket can be closed:

- [x] Amber wants us to see if OICR needs to archive anything from the v1 website (legal meeting for discussion on Monday May 16) --> Confirm with @mcourtot 
Confirmed 17/05/2023 with Amber and Judith, no further action needed
